#!/usr/bin/env bash
# Batch-run TripoSR on the 23 user-provided creature crops.
#
# Uses crops produced by scripts/triposr/crop_user_art.py (one per creature,
# stored in /tmp/cubicraftia_creature_crops/). Each crop is the actual brick-
# built reference art the user provided, so TripoSR preserves the colour
# information via vertex colours / texture — no palette post-process needed.
#
# Per-asset wall time on M4 MPS: ~1:40. Total ~38 min.
#
# Usage:
#   bash scripts/triposr/batch_from_user_art.sh
#
# License: GPL-3.0-or-later.

set -euo pipefail

REPO="/Users/jnuyens/src/Cubicraftia"
TRIPOSR_DIR="/Users/jnuyens/ai-tools/TripoSR"
CROPS_DIR="/tmp/cubicraftia_creature_crops"
WORK_DIR="/tmp/cubicraftia_triposr_work"
OUT_DIR="$REPO/assets/meshes/creatures"

CREATURES=(
  # 5 hostiles
  laser_penguin ghost vampire_humanoid vampire_bat bat
  cube_slime_large cube_slime_medium cube_slime_small
  # 13 wildlife
  panda desert_mouse reindeer snowman monkey toucan elephant
  giraffe gnu manta orca
  fish_blue fish_orange fish_yellow jellyfish
)

mkdir -p "$WORK_DIR" "$OUT_DIR"
cd "$TRIPOSR_DIR"
source venv/bin/activate

TOTAL=${#CREATURES[@]}
START_TIME=$(date +%s)

echo "=========================================="
echo "Cubicraftia TripoSR batch (user art): $TOTAL"
echo "Crops:  $CROPS_DIR"
echo "Output: $OUT_DIR/<name>_triposr.glb"
echo "Started: $(date)"
echo "=========================================="

for i in "${!CREATURES[@]}"; do
  name="${CREATURES[$i]}"
  idx=$((i + 1))
  echo ""
  echo "[$idx/$TOTAL] $name ..."

  CROP="$CROPS_DIR/${name}.png"
  TMP_OUT="$WORK_DIR/${name}_out"
  if [ ! -f "$CROP" ]; then
    echo "  ✗ missing crop $CROP — skipping"
    continue
  fi

  rm -rf "$TMP_OUT"
  python "$TRIPOSR_DIR/run.py" "$CROP" \
    --output-dir "$TMP_OUT" \
    --device mps \
    --model-save-format glb \
    2>&1 | grep -E "(INFO -|ERROR|Traceback)" | tail -5 || true

  if [ -f "$TMP_OUT/0/mesh.glb" ]; then
    cp "$TMP_OUT/0/mesh.glb" "$OUT_DIR/${name}_triposr.glb"
    cat > "$OUT_DIR/${name}_triposr.glb.license" << 'LICENSE_EOF'
SPDX-FileCopyrightText: 2026 Cubicraftia contributors
SPDX-License-Identifier: GPL-3.0-or-later
Generated by Stability AI / Tripo AI TripoSR (MIT) from a user-provided
Cubicraftia brick-built reference image (cropped per creature). TripoSR is
MIT licensed; generated meshes inherit MIT-compatible terms.
LICENSE_EOF
    size_kb=$(($(stat -f%z "$OUT_DIR/${name}_triposr.glb") / 1024))
    elapsed=$(($(date +%s) - START_TIME))
    echo "  ✓ ${name}_triposr.glb (${size_kb} KB), wall time so far: $((elapsed / 60))m $((elapsed % 60))s"
  else
    echo "  ✗ TripoSR did not produce mesh.glb"
  fi
done

ELAPSED=$(($(date +%s) - START_TIME))
echo ""
echo "=========================================="
echo "Batch complete: $TOTAL creatures in $((ELAPSED / 60))m $((ELAPSED % 60))s"
echo "=========================================="
