#!/usr/bin/env bash
# Batch-run TripoSR on all 23 Cubicraftia creatures.
#
# Generates reference silhouette → runs TripoSR → saves mesh.glb to
# assets/meshes/creatures/<name>_triposr.glb.
#
# Per-asset wall time on M4 MPS: ~1:40. Total estimated: ~38 min.
#
# Usage:
#   bash scripts/triposr/batch_creatures.sh
#
# License: GPL-3.0-or-later.

set -euo pipefail

REPO="/Users/jnuyens/src/Cubicraftia"
TRIPOSR_DIR="/Users/jnuyens/ai-tools/TripoSR"
REFS_DIR="/tmp/cubicraftia_creature_refs"
OUT_DIR="$REPO/assets/meshes/creatures"

CREATURES=(
  # Hostiles (5)
  laser_penguin ghost vampire_humanoid vampire_bat bat
  cube_slime_large cube_slime_medium cube_slime_small
  # Atmospheric wildlife (13 + variants)
  panda desert_mouse reindeer snowman monkey toucan elephant
  giraffe gnu manta orca
  fish_blue fish_orange fish_yellow jellyfish
)

mkdir -p "$REFS_DIR" "$OUT_DIR"
cd "$TRIPOSR_DIR"
source venv/bin/activate

TOTAL=${#CREATURES[@]}
START_TIME=$(date +%s)

echo "=========================================="
echo "Cubicraftia TripoSR batch: $TOTAL creatures"
echo "Output: $OUT_DIR"
echo "Refs:   $REFS_DIR"
echo "Started: $(date)"
echo "=========================================="

for i in "${!CREATURES[@]}"; do
  name="${CREATURES[$i]}"
  idx=$((i + 1))
  echo ""
  echo "[$idx/$TOTAL] $name ..."
  REF_PATH="$REFS_DIR/${name}.png"
  TMP_OUT="$REFS_DIR/${name}_out"

  # Step 1: generate silhouette
  python3 "$REPO/scripts/triposr/generate_reference_image.py" "$name" --out "$REF_PATH" || { echo "  ✗ ref gen failed"; continue; }

  # Step 2: TripoSR
  rm -rf "$TMP_OUT"
  python "$TRIPOSR_DIR/run.py" "$REF_PATH" \
    --output-dir "$TMP_OUT" \
    --device mps \
    --model-save-format glb \
    2>&1 | grep -E "(INFO -|ERROR|Traceback)" | tail -5 || true

  # Step 3: move output
  if [ -f "$TMP_OUT/0/mesh.glb" ]; then
    cp "$TMP_OUT/0/mesh.glb" "$OUT_DIR/${name}_triposr.glb"
    cat > "$OUT_DIR/${name}_triposr.glb.license" << 'LICENSE_EOF'
SPDX-FileCopyrightText: 2026 Cubicraftia contributors
SPDX-License-Identifier: GPL-3.0-or-later
Generated by Stability AI / Tripo AI TripoSR (MIT) from a Cubicraftia voxel
silhouette (scripts/triposr/generate_reference_image.py). TripoSR is MIT
licensed; generated meshes inherit MIT-compatible terms.
LICENSE_EOF
    size_kb=$(($(stat -f%z "$OUT_DIR/${name}_triposr.glb") / 1024))
    elapsed=$(($(date +%s) - START_TIME))
    echo "  ✓ ${name}_triposr.glb (${size_kb} KB), wall time so far: $((elapsed / 60))m $((elapsed % 60))s"
  else
    echo "  ✗ TripoSR did not produce mesh.glb"
  fi
done

ELAPSED=$(($(date +%s) - START_TIME))
echo ""
echo "=========================================="
echo "Batch complete: $TOTAL creatures in $((ELAPSED / 60))m $((ELAPSED % 60))s"
echo "Outputs at: $OUT_DIR/*_triposr.glb"
echo "=========================================="
