"""
Cubicraftia 2D icon + title artwork generator (Pillow, no GPU).

Generates every PNG asset listed in docs/art-direction-brief.md §3 except the
avatar preset thumbnails (those come from scripts/generate_builder.py).

Output paths follow the brief verbatim — replacing the 1×1 transparent stubs
that v1.0 ships with. Re-running is safe; outputs are overwritten.

Anchored to the Cubicraftia palette (cubicraftia.tres / art-direction-brief §1.3).

Usage:
    python3 scripts/generate_icons.py

License: GPL-3.0-or-later.
"""

import os
import math
from PIL import Image, ImageDraw, ImageFilter, ImageFont

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ICON_DIR = os.path.join(REPO, "assets", "textures", "icons")
FONT_REG = os.path.join(REPO, "assets", "fonts", "NotoSans-Regular.ttf")
FONT_BOLD = os.path.join(REPO, "assets", "fonts", "NotoSans-SemiBold.ttf")

# Palette (RGBA tuples)
NAVY = (27, 44, 86, 255)
BRICK_WHITE = (241, 240, 234, 255)
ACCENT = (245, 195, 13, 255)
DEST_RED = (214, 56, 40, 255)
GREEN = (61, 181, 96, 255)
AMBER = (232, 137, 12, 255)
GRAY = (107, 114, 128, 255)
TRANS = (0, 0, 0, 0)


# ─── Helpers ──────────────────────────────────────────────────────────────────

def new_img(size):
    """Create a transparent RGBA image at 3× the target size for supersampling."""
    return Image.new("RGBA", (size * 3, size * 3), TRANS)


def downsample(img, target_size):
    """High-quality downsample with LANCZOS."""
    return img.resize((target_size, target_size), Image.LANCZOS)


def save(img, name, target_size):
    """Save a 3×-authored image to icon directory at target_size."""
    path = os.path.join(ICON_DIR, name)
    out = downsample(img, target_size) if img.size[0] != target_size else img
    out.save(path, optimize=True)
    write_license(path)
    return path


def save_explicit(img, name):
    """Save image at its native size (no downsample)."""
    path = os.path.join(ICON_DIR, name)
    img.save(path, optimize=True)
    write_license(path)
    return path


def write_license(png_path):
    """SPDX sidecar in project convention."""
    with open(png_path + ".license", "w") as fh:
        fh.write(
            "SPDX-FileCopyrightText: 2026 Cubicraftia contributors\n"
            "SPDX-License-Identifier: GPL-3.0-or-later\n"
            "Generated by scripts/generate_icons.py.\n"
        )


def soft_shadow(img, offset_y=4, blur=4, opacity=64):
    """Drop a soft shadow underneath the alpha mask (returns new RGBA)."""
    shadow = Image.new("RGBA", img.size, TRANS)
    alpha = img.split()[3]
    shadow.paste((0, 0, 0, opacity), (0, offset_y), alpha)
    shadow = shadow.filter(ImageFilter.GaussianBlur(blur))
    out = Image.alpha_composite(shadow, img)
    return out


# ─── Icon constructors ────────────────────────────────────────────────────────

def icon_friends(target=32):
    img = new_img(target)
    d = ImageDraw.Draw(img)
    # Two cube-head silhouettes — back one slightly smaller/dimmer
    w = img.size[0]
    # Back head
    bx, by, bs = w * 0.55, w * 0.30, w * 0.32
    d.rounded_rectangle((bx, by, bx + bs, by + bs), radius=bs * 0.18, fill=(*BRICK_WHITE[:3], 180))
    # Body for back head
    d.rounded_rectangle((bx - bs * 0.1, by + bs, bx + bs * 1.1, w * 0.95), radius=w * 0.05, fill=(*BRICK_WHITE[:3], 180))
    # Front head
    fx, fy, fs = w * 0.10, w * 0.35, w * 0.38
    d.rounded_rectangle((fx, fy, fx + fs, fy + fs), radius=fs * 0.18, fill=BRICK_WHITE)
    # Front body
    d.rounded_rectangle((fx - fs * 0.1, fy + fs, fx + fs * 1.1, w * 0.97), radius=w * 0.05, fill=BRICK_WHITE)
    return save(img, "icon_friends.png", target)


def icon_signal(active_bars, target=16):
    img = new_img(target)
    d = ImageDraw.Draw(img)
    w = img.size[0]
    # 3 vertical bars increasing in height. Colors: signal_1 amber, signal_2 yellow, signal_3 green.
    bar_w = w * 0.18
    gap = w * 0.08
    base_y = w * 0.85
    heights = [w * 0.30, w * 0.55, w * 0.80]
    total_w = bar_w * 3 + gap * 2
    start_x = (w - total_w) / 2
    colors = [AMBER, ACCENT, GREEN]
    for i in range(3):
        x = start_x + i * (bar_w + gap)
        y_top = base_y - heights[i]
        if i < active_bars:
            color = colors[active_bars - 1]
        else:
            color = (*BRICK_WHITE[:3], 60)
        d.rounded_rectangle((x, y_top, x + bar_w, base_y), radius=bar_w * 0.2, fill=color)
    return save(img, f"icon_signal_{active_bars}.png", target)


def icon_mute(target=16):
    img = new_img(target)
    d = ImageDraw.Draw(img)
    w = img.size[0]
    # Speaker silhouette (trapezoid)
    pts = [(w * 0.20, w * 0.40), (w * 0.36, w * 0.40),
           (w * 0.50, w * 0.25), (w * 0.50, w * 0.75),
           (w * 0.36, w * 0.60), (w * 0.20, w * 0.60)]
    d.polygon(pts, fill=(*BRICK_WHITE[:3], 200))
    # Slash
    d.line((w * 0.60, w * 0.25, w * 0.85, w * 0.78), fill=DEST_RED, width=int(w * 0.07))
    return save(img, "icon_mute.png", target)


def icon_freeze(target=16):
    img = new_img(target)
    d = ImageDraw.Draw(img)
    w = img.size[0]
    cx, cy = w / 2, w / 2
    r = w * 0.40
    # 6-point snowflake
    for angle_deg in range(0, 360, 60):
        a = math.radians(angle_deg)
        x2 = cx + math.cos(a) * r
        y2 = cy + math.sin(a) * r
        d.line((cx, cy, x2, y2), fill=ACCENT, width=int(w * 0.08))
        # Small branches at 2/3 of the spike
        bx = cx + math.cos(a) * r * 0.6
        by = cy + math.sin(a) * r * 0.6
        for branch_offset in (40, -40):
            ba = math.radians(angle_deg + branch_offset)
            bx2 = bx + math.cos(ba) * r * 0.25
            by2 = by + math.sin(ba) * r * 0.25
            d.line((bx, by, bx2, by2), fill=ACCENT, width=int(w * 0.05))
    return save(img, "icon_freeze.png", target)


def icon_spinner(target=32):
    img = new_img(target)
    d = ImageDraw.Draw(img)
    w = img.size[0]
    cx, cy = w / 2, w / 2
    outer = w * 0.40
    inner = w * 0.28
    # Dashed arc — 8 segments, alternating opacity
    for seg in range(8):
        a0 = seg * 45
        a1 = a0 + 30
        opacity = int(255 * (seg / 8.0)) + 30   # gradient
        d.arc(
            (cx - outer, cy - outer, cx + outer, cy + outer),
            start=a0, end=a1,
            fill=(*BRICK_WHITE[:3], min(opacity, 255)),
            width=int(w * 0.10),
        )
    return save(img, "icon_spinner.png", target)


def icon_error(target=16):
    img = new_img(target)
    d = ImageDraw.Draw(img)
    w = img.size[0]
    cx, cy = w / 2, w / 2
    d.ellipse((cx - w * 0.40, cy - w * 0.40, cx + w * 0.40, cy + w * 0.40), fill=DEST_RED)
    # ! in white
    d.rectangle((cx - w * 0.05, cy - w * 0.20, cx + w * 0.05, cy + w * 0.10), fill=BRICK_WHITE)
    d.ellipse((cx - w * 0.06, cy + w * 0.16, cx + w * 0.06, cy + w * 0.28), fill=BRICK_WHITE)
    return save(img, "icon_error.png", target)


def icon_warning(target=16):
    img = new_img(target)
    d = ImageDraw.Draw(img)
    w = img.size[0]
    # Navy triangle on transparent (since this sits on amber StyleBox_warning_banner)
    pts = [(w * 0.5, w * 0.12), (w * 0.92, w * 0.85), (w * 0.08, w * 0.85)]
    d.polygon(pts, fill=NAVY)
    # White exclamation mark in centre
    d.rectangle((w * 0.46, w * 0.35, w * 0.54, w * 0.62), fill=BRICK_WHITE)
    d.ellipse((w * 0.45, w * 0.66, w * 0.55, w * 0.76), fill=BRICK_WHITE)
    return save(img, "icon_warning.png", target)


def icon_email(target=48):
    img = new_img(target)
    d = ImageDraw.Draw(img)
    w = img.size[0]
    # Envelope outline
    pad = w * 0.15
    body_box = (pad, w * 0.30, w - pad, w * 0.80)
    d.rounded_rectangle(body_box, radius=w * 0.03, outline=NAVY, width=int(w * 0.04), fill=BRICK_WHITE)
    # Flap (V from top corners to centre)
    d.line((pad, w * 0.30, w / 2, w * 0.55), fill=NAVY, width=int(w * 0.04))
    d.line((w / 2, w * 0.55, w - pad, w * 0.30), fill=NAVY, width=int(w * 0.04))
    # Small green check in bottom-right (confirms consent received)
    cx, cy = w * 0.78, w * 0.78
    d.ellipse((cx - w * 0.10, cy - w * 0.10, cx + w * 0.10, cy + w * 0.10), fill=GREEN)
    d.line((cx - w * 0.05, cy, cx - w * 0.01, cy + w * 0.04), fill=BRICK_WHITE, width=int(w * 0.025))
    d.line((cx - w * 0.01, cy + w * 0.04, cx + w * 0.06, cy - w * 0.04), fill=BRICK_WHITE, width=int(w * 0.025))
    return save(img, "icon_email.png", target)


def icon_check(target=16):
    img = new_img(target)
    d = ImageDraw.Draw(img)
    w = img.size[0]
    # Bold check mark
    d.line((w * 0.18, w * 0.50, w * 0.40, w * 0.72), fill=BRICK_WHITE, width=int(w * 0.10))
    d.line((w * 0.40, w * 0.72, w * 0.85, w * 0.25), fill=BRICK_WHITE, width=int(w * 0.10))
    return save(img, "icon_check.png", target)


def icon_plus(target=24):
    img = new_img(target)
    d = ImageDraw.Draw(img)
    w = img.size[0]
    arm = w * 0.30
    cx, cy = w / 2, w / 2
    bar_t = w * 0.10
    d.rounded_rectangle((cx - arm, cy - bar_t / 2, cx + arm, cy + bar_t / 2), radius=bar_t / 2, fill=BRICK_WHITE)
    d.rounded_rectangle((cx - bar_t / 2, cy - arm, cx + bar_t / 2, cy + arm), radius=bar_t / 2, fill=BRICK_WHITE)
    return save(img, "icon_plus.png", target)


def icon_arrow_down(target=16):
    img = new_img(target)
    d = ImageDraw.Draw(img)
    w = img.size[0]
    color = (*BRICK_WHITE[:3], 180)
    d.line((w * 0.20, w * 0.40, w * 0.50, w * 0.65), fill=color, width=int(w * 0.10))
    d.line((w * 0.50, w * 0.65, w * 0.80, w * 0.40), fill=color, width=int(w * 0.10))
    return save(img, "icon_arrow_down.png", target)


def icon_dice(target=24):
    img = new_img(target)
    d = ImageDraw.Draw(img)
    w = img.size[0]
    # Square die face
    pad = w * 0.18
    d.rounded_rectangle((pad, pad, w - pad, w - pad), radius=w * 0.08, fill=BRICK_WHITE)
    # Dots arranged "5"
    dot_r = w * 0.06
    positions = [(0.30, 0.30), (0.70, 0.30), (0.50, 0.50), (0.30, 0.70), (0.70, 0.70)]
    for px, py in positions:
        cx, cy = w * px, w * py
        d.ellipse((cx - dot_r, cy - dot_r, cx + dot_r, cy + dot_r), fill=NAVY)
    return save(img, "icon_dice.png", target)


def ftue_arrow(target=128):
    img = new_img(target)
    d = ImageDraw.Draw(img)
    w = img.size[0]
    # Chunky downward arrow — shaft + arrowhead, slight tilt
    pad = w * 0.20
    shaft_w = w * 0.18
    cx = w / 2
    shaft_top = w * 0.10
    shaft_bot = w * 0.62
    head_top = w * 0.55
    head_bot = w * 0.85
    head_w = w * 0.45
    # Outline navy
    arrow_pts_outer = [
        (cx - shaft_w, shaft_top),
        (cx + shaft_w, shaft_top),
        (cx + shaft_w, head_top),
        (cx + head_w, head_top),
        (cx, head_bot),
        (cx - head_w, head_top),
        (cx - shaft_w, head_top),
    ]
    # Draw outline first (slightly larger polygon for stroke effect)
    stroke = int(w * 0.03)
    d.polygon(arrow_pts_outer, fill=NAVY)
    # Then fill arrow_pts shrunk by stroke
    arrow_pts_inner = []
    for x, y in arrow_pts_outer:
        # shrink towards center
        dx = x - cx
        dy = y - w * 0.5
        scale = 0.90
        arrow_pts_inner.append((cx + dx * scale, w * 0.5 + dy * scale))
    d.polygon(arrow_pts_inner, fill=ACCENT)
    # Eye + smile on arrowhead
    eye_x, eye_y = cx - w * 0.06, head_top + w * 0.05
    d.ellipse((eye_x - w * 0.025, eye_y - w * 0.025, eye_x + w * 0.025, eye_y + w * 0.025), fill=NAVY)
    # Smile arc
    d.arc((cx - w * 0.10, head_top + w * 0.02, cx + w * 0.08, head_top + w * 0.16),
          start=10, end=170, fill=NAVY, width=int(w * 0.015))
    return save(img, "ftue_arrow.png", target)


# ─── Title screen artwork ─────────────────────────────────────────────────────

def title_bg(target=512):
    """Seamlessly tileable brick-stud pattern for title background."""
    img = Image.new("RGB", (target, target), NAVY[:3])
    d = ImageDraw.Draw(img)
    stud_pitch = target // 32   # 32 studs across
    stud_d = int(stud_pitch * 0.70)
    # Slightly different alpha tints for visual interest
    for sy in range(0, target + stud_pitch, stud_pitch):
        for sx in range(0, target + stud_pitch, stud_pitch):
            # Offset every other row to suggest stagger
            x_off = (stud_pitch // 2) if (sy // stud_pitch) % 2 == 1 else 0
            cx = sx + x_off
            cy = sy
            # Wrap for seamless tiling
            cx %= target
            cy %= target
            # Vary color: most navy-tinted, occasional yellow / brick-white accent
            seed = (cx * 31 + cy * 17) % 100
            if seed < 70:
                color = (40, 60, 100)   # slightly lighter navy
            elif seed < 90:
                color = (60, 80, 130)   # even lighter navy
            elif seed < 96:
                color = BRICK_WHITE[:3]
            else:
                color = ACCENT[:3]
            d.ellipse((cx - stud_d // 2, cy - stud_d // 2, cx + stud_d // 2, cy + stud_d // 2), fill=color)
    img.save(os.path.join(ICON_DIR, "title_bg.png"), optimize=True)
    write_license(os.path.join(ICON_DIR, "title_bg.png"))


def wordmark():
    """Cubicraftia wordmark — NotoSans SemiBold at 96 px, 1024x256."""
    img = Image.new("RGBA", (1024, 256), TRANS)
    d = ImageDraw.Draw(img)
    try:
        font = ImageFont.truetype(FONT_BOLD, 110)
    except Exception:
        font = ImageFont.load_default()
    text = "Cubicraftia"
    # Centre measure
    bbox = d.textbbox((0, 0), text, font=font)
    tw = bbox[2] - bbox[0]
    th = bbox[3] - bbox[1]
    tx = (1024 - tw) // 2 - bbox[0]
    ty = (256 - th) // 2 - bbox[1]
    d.text((tx, ty), text, font=font, fill=BRICK_WHITE)
    # Accent yellow underline on final stroke (under the "a")
    underline_y = ty + th + 8
    underline_x_start = tx + int(tw * 0.85)
    underline_x_end = tx + tw
    d.rectangle((underline_x_start, underline_y, underline_x_end, underline_y + 4), fill=ACCENT)
    img.save(os.path.join(ICON_DIR, "cubicraftia_wordmark.png"), optimize=True)
    write_license(os.path.join(ICON_DIR, "cubicraftia_wordmark.png"))


def world_thumb_placeholder():
    """Default world thumbnail — 2x4 brick on navy with ? overlay."""
    img = Image.new("RGB", (256, 144), NAVY[:3])
    d = ImageDraw.Draw(img)
    # Dotted-line border
    for x in range(0, 256, 8):
        d.point((x, 4), fill=BRICK_WHITE[:3])
        d.point((x, 139), fill=BRICK_WHITE[:3])
    for y in range(0, 144, 8):
        d.point((4, y), fill=BRICK_WHITE[:3])
        d.point((251, y), fill=BRICK_WHITE[:3])
    # 2x4 brick silhouette in centre
    bw, bh = 90, 35
    bx, by = (256 - bw) // 2, (144 - bh) // 2 - 5
    d.rounded_rectangle((bx, by, bx + bw, by + bh), radius=4, fill=ACCENT[:3])
    # 8 studs on top (2x4)
    for col in range(4):
        for row in range(2):
            sx = bx + 10 + col * 20
            sy = by + 8 + row * 14
            d.ellipse((sx - 4, sy - 4, sx + 4, sy + 4), fill=(180, 140, 5))
    # "?" overlay below
    try:
        font = ImageFont.truetype(FONT_BOLD, 32)
    except Exception:
        font = ImageFont.load_default()
    d.text((118, 95), "?", font=font, fill=BRICK_WHITE[:3])
    img.save(os.path.join(ICON_DIR, "world_thumb_placeholder.png"), optimize=True)
    write_license(os.path.join(ICON_DIR, "world_thumb_placeholder.png"))


# ─── Main ─────────────────────────────────────────────────────────────────────

def main():
    os.makedirs(ICON_DIR, exist_ok=True)
    print(f"Cubicraftia icon generator → {ICON_DIR}\n")

    generated = []

    # Network status icons
    for n in (1, 2, 3):
        p = icon_signal(n)
        generated.append(p)
        print(f"  ✓ {os.path.basename(p)}")

    for name, fn in [
        ("icon_friends.png",       icon_friends),
        ("icon_mute.png",          icon_mute),
        ("icon_freeze.png",        icon_freeze),
        ("icon_spinner.png",       icon_spinner),
        ("icon_error.png",         icon_error),
        ("icon_warning.png",       icon_warning),
        ("icon_email.png",         icon_email),
        ("icon_check.png",         icon_check),
        ("icon_plus.png",          icon_plus),
        ("icon_arrow_down.png",    icon_arrow_down),
        ("icon_dice.png",          icon_dice),
        ("ftue_arrow.png",         ftue_arrow),
    ]:
        p = fn()
        generated.append(p)
        print(f"  ✓ {name}")

    # Title screen artwork
    title_bg()
    generated.append(os.path.join(ICON_DIR, "title_bg.png"))
    print("  ✓ title_bg.png (512x512 seamless brick pattern)")

    wordmark()
    generated.append(os.path.join(ICON_DIR, "cubicraftia_wordmark.png"))
    print("  ✓ cubicraftia_wordmark.png (1024x256)")

    world_thumb_placeholder()
    generated.append(os.path.join(ICON_DIR, "world_thumb_placeholder.png"))
    print("  ✓ world_thumb_placeholder.png (256x144)")

    print(f"\nGenerated {len(generated)} assets.")


if __name__ == "__main__":
    main()
