# SPDX-FileCopyrightText: 2026 Cubicraftia contributors
# SPDX-License-Identifier: GPL-3.0-or-later
#
# test_invite_token.gd — Unit tests for invite link token generation and validation.
#
# Invite token contract (04-CONTEXT.md Area 3):
#   - Random 128-bit token, base32-encoded → exactly 26 ASCII characters
#   - Single-use: once redeemed (redeemed_by != null), the token is invalid
#   - 24-hour TTL: tokens with expires_at in the past are expired
#
# These tests exercise FriendsClient._generate_invite_token() and _is_invite_valid()
# without requiring a live Supabase connection.
#
# Anchors:
#   04-CONTEXT.md Area 3 — invite tokens (128-bit, base32, single-use, 24h TTL)
#   DOCS.md §6.3 — invite link behaviour
#   04-04-PLAN.md Task 1 — FriendsClient implementation

extends GutTest

const FriendsClientScript = preload("res://src/autoload/friends_client.gd")

# Do NOT add FriendsClient to the scene tree — _ready() creates HTTPRequest nodes
# and a Timer that require a live scene, which would leak and interfere with later tests.

var _fc: Node = null


func before_each() -> void:
	_fc = FriendsClientScript.new()


func after_each() -> void:
	if is_instance_valid(_fc):
		_fc.free()
	_fc = null


# ─── Invite token tests ────────────────────────────────────────────────────────

## test_token_length: token generated by _generate_invite_token() must be exactly 26 chars.
func test_token_length() -> void:
	var token: String = _fc._generate_invite_token()
	assert_eq(token.length(), 26,
		"Invite token must be exactly 26 characters (128-bit base32)")


## test_token_alphabet: every character must be from the base32 alphabet [a-z2-7].
func test_token_alphabet() -> void:
	var token: String = _fc._generate_invite_token()
	var regex := RegEx.new()
	regex.compile("^[a-z2-7]+$")
	assert_true(regex.search(token) != null,
		"All characters in the token must be from the base32 alphabet (a-z, 2-7)")


## test_token_uniqueness: two calls to _generate_invite_token() should (overwhelmingly)
## produce different tokens. This is a probabilistic test — collision probability is
## 1/32^26 ≈ 10^-39, so it is safe to assert inequality.
func test_token_uniqueness() -> void:
	var t1: String = _fc._generate_invite_token()
	var t2: String = _fc._generate_invite_token()
	assert_ne(t1, t2,
		"Two independently generated tokens must differ (collision probability is negligible)")


## test_expired_token_rejected: a token with expires_at in the past is invalid.
func test_expired_token_rejected() -> void:
	var expired_inv := {
		"token": "abcdefghijklmnopqrst234567",
		"expires_at": Time.get_unix_time_from_system() - 1.0,  # 1 second in the past
		"redeemed_by": null,
	}
	assert_false(FriendsClientScript._is_invite_valid(expired_inv),
		"An invite with expires_at in the past must be rejected")


## test_single_use_enforced: a token that has already been redeemed (redeemed_by set) is invalid.
func test_single_use_enforced() -> void:
	var redeemed_inv := {
		"token": "aaaaaaaaaaaaaaaaaaaaaaaaaa",
		"expires_at": Time.get_unix_time_from_system() + 3600.0,  # still valid TTL
		"redeemed_by": "some-user-uid",  # already redeemed
	}
	assert_false(FriendsClientScript._is_invite_valid(redeemed_inv),
		"A token that has already been redeemed must be rejected")


## test_valid_token_accepted: a fresh token with future expiry and no redeemed_by is valid.
func test_valid_token_accepted() -> void:
	var fresh_inv := {
		"token": _fc._generate_invite_token(),
		"expires_at": Time.get_unix_time_from_system() + 86400.0,  # 24 hours from now
		"redeemed_by": null,
	}
	assert_true(FriendsClientScript._is_invite_valid(fresh_inv),
		"A fresh token with future expiry and no redemption must be accepted")


## test_24h_ttl_expiry: token expires exactly at the boundary.
## One second before expiry → valid. One second after → invalid.
func test_24h_ttl_expiry() -> void:
	var now := Time.get_unix_time_from_system()
	var nearly_expired := {"token": "xxxxxxxxxxxxxxxxxxxxxxxxxx", "expires_at": now + 1.0, "redeemed_by": null}
	var just_expired   := {"token": "xxxxxxxxxxxxxxxxxxxxxxxxxx", "expires_at": now - 1.0, "redeemed_by": null}
	assert_true(FriendsClientScript._is_invite_valid(nearly_expired),
		"Token expiring 1 second from now must still be valid")
	assert_false(FriendsClientScript._is_invite_valid(just_expired),
		"Token that expired 1 second ago must be invalid")
