# SPDX-FileCopyrightText: 2026 Cubicraftia contributors
# SPDX-License-Identifier: GPL-3.0-or-later
#
# test_friends_schema.gd — Unit tests for the Supabase friends graph schema.
#
# Friends schema (04-CONTEXT.md Area 3):
#   friendships(user_a UUID, user_b UUID, created_at, status)
#   CHECK (user_a < user_b) — canonical ordering: smaller UUID is always user_a
#   Row-Level Security: a user can SELECT a row only if they appear in user_a or user_b
#
# These tests verify the client-side canonical ordering logic in FriendsClient._canonical_pair()
# without requiring a live Supabase connection.
#
# Anchors:
#   04-CONTEXT.md Area 3 — friends schema + canonical ordering + RLS
#   04-04-PLAN.md Task 1 — FriendsClient implementation

extends GutTest

const FriendsClientScript = preload("res://src/autoload/friends_client.gd")

# _canonical_pair and _is_invite_valid are static functions — call them on the script
# without instantiating. _generate_invite_token is an instance function.

var _fc: Node = null


func before_each() -> void:
	# Instantiate to access the non-static _generate_invite_token.
	# Do NOT add to scene tree to avoid _ready() side effects (timer, HTTPRequest nodes).
	_fc = FriendsClientScript.new()


func after_each() -> void:
	if is_instance_valid(_fc):
		_fc.free()
	_fc = null


# ─── Friends schema tests ──────────────────────────────────────────────────────

## test_canonical_ordering: _canonical_pair always places the lexicographically smaller
## UUID in position 0 (user_a), mirroring Postgres CHECK (user_a < user_b).
func test_canonical_ordering() -> void:
	var result := FriendsClientScript._canonical_pair("z-uuid-large", "a-uuid-small")
	assert_eq(result[0], "a-uuid-small",
		"Smaller UUID must always be in position 0 (user_a)")
	assert_eq(result[1], "z-uuid-large",
		"Larger UUID must always be in position 1 (user_b)")


## test_canonical_ordering_already_ordered: if inputs are already in order, output unchanged.
func test_canonical_ordering_already_ordered() -> void:
	var result := FriendsClientScript._canonical_pair("a-uid-first", "z-uid-second")
	assert_eq(result[0], "a-uid-first",
		"If already ordered, user_a should remain the smaller UUID")
	assert_eq(result[1], "z-uid-second",
		"If already ordered, user_b should remain the larger UUID")


## test_duplicate_rejected (idempotent ordering): calling _canonical_pair twice with the
## same pair must return the same value, confirming canonical uniqueness.
func test_duplicate_rejected() -> void:
	var pair_a := FriendsClientScript._canonical_pair("uid-beta", "uid-alpha")
	var pair_b := FriendsClientScript._canonical_pair("uid-alpha", "uid-beta")
	assert_eq(pair_a[0], pair_b[0],
		"Canonical user_a must be identical regardless of argument order")
	assert_eq(pair_a[1], pair_b[1],
		"Canonical user_b must be identical regardless of argument order")


## test_invite_token_format: the invite token generated by FriendsClient must match
## the 26-char base32 alphabet (^[a-z2-7]{26}$).
func test_invite_token_format() -> void:
	var token: String = _fc._generate_invite_token()
	assert_eq(token.length(), 26,
		"Invite token must be exactly 26 characters")
	var regex := RegEx.new()
	regex.compile("^[a-z2-7]{26}$")
	assert_true(regex.search(token) != null,
		"Every character in the token must be in the base32 alphabet (a-z, 2-7)")
